import numpy as np <br>
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ] <br>
array_list = np.array(object = list_) <br><br>
<font color="red">
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.</font>

In [1]:
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object=list_)

<font color='red'>Answer:-</font>
Yes, there is a difference in the data type of variables list_ and array_list.
In this code 'list_' is a python list while 'array_list' is a numpy array.

In [7]:
print("data type of list_",type(list_))
print("data type of array_list",type(array_list))

data type of list_ <class 'list'>
data type of array_list <class 'numpy.ndarray'>


<font color="red">Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.</font>

In [9]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


<font color="red">Q3. Considering the following changes in the variable, array_list: <br><br>
array_list = np.array(object = list_, dtype = int) <br><br>
Will there be any difference in the data type of the elements present in both the variables, list_ and
array_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.</font>

<font color="red">Answer :-</font>


In [16]:
array_list=np.array(object=list_,dtype=int)
print(array_list)
print(list_)

[1 2 3 4 5]
['1', '2', '3', '4', '5']


yes,there will be differnece in the datatype of the elements present in both the variables list_ and array_list

In [17]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [20]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


<font color="red">
Consider the below code to answer further questions:<br>
import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ] <br>
num_array = np.array(object = num_list) 
</font>

In [29]:
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)
print("num_list :",num_list)
print()
print("num_array :",num_array)

num_list : [[1, 2, 3], [4, 5, 6]]

num_array : [[1 2 3]
 [4 5 6]]


<font color="red">Q4. Write a code to find the following characteristics of variable, num_array: <br>
(i) shape<br>
(ii) size
</font>

<font color="red">Answer i. :-</font>

In [34]:
num_array.shape

(2, 3)

<font color="red">Answer ii. :-</font>

In [38]:
num_array.size

6

<font color="red">Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.</font>

<font color="red">Answer: </font>

In [43]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<font color="red">Q6. Create an identity matrix of shape (5,5) using numpy functions? </font>

<font color="red">Answer:</font>

In [48]:
mtx=np.zeros((5,5),dtype=int)
mtx

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
np.fill_diagonal(mtx,1)

In [50]:
mtx

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
# ----------------------- completed -------------------------------------